import TitleSection from "@/components/TitleSection";
import Image from "next/image";
import servImg from '../../public/services.jpg'
import { servicePriceItems, servicePriceItemsSecond, servicePriceItemsThird } from "@/data/data";
import TitleName from "@/partials/TitleName";
import LineRun from "@/partials/LIneRun";
import { Metadata } from "next";
import * as motion from "motion/react-client"
import { containerStagger, fadeIn, fadeInOpacity } from "@/motion/animation";

export const metadata: Metadata = {
    title: 'Services - Photography as art',
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <>
            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className="py-20">
                <div className="container">
                    <div className="relative overflow-hidden">
                        <motion.div variants={fadeInOpacity} className="">
                            <Image src={servImg} alt='' className='rounded-2xl' />
                        </motion.div>
                        <div className="bg-main absolute top-0 right-0  max-w-160 p-5 rounded-bl-2xl">
                            <div className="flex justify-between items-center">
                                <TitleSection desc="services" title="diverce photography offerings" />
                            </div>
                            <motion.p variants={fadeIn} className='text-desc'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci dicta fugit reprehenderit eaque esse qui voluptatem provident voluptatum nostrum ipsa.</motion.p>
                        </div>
                        <div className="bg-main absolute bottom-0 left-0 rounded-tr-2xl p-5">
                            <Image src={'page-banner-shape.svg'} alt='' width={100} height={100} />
                        </div>
                        <div className="absolute bg-main p-5 bottom-0 right-0 text-desc rounded-tl-2xl">
                            Scroll down to see all the services
                        </div>
                    </div>
                    <div className="grid grid-cols-2 gap-10 mt-30">
                        <div>
                            <motion.h3 variants={fadeIn} className="uppercase text-desc text-2xl mb-5">portrait photography</motion.h3>
                            <motion.p variants={fadeIn} className="text-desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi distinctio alias pariatur laboriosam magni corporis sapiente omnis natus rem. Maxime nihil dolorem molestiae quasi voluptas officia nemo excepturi unde voluptatibus quisquam assumenda amet animi, nisi exercitationem cumque quod quaerat? Culpa incidunt a ab mollitia aspernatur illo ipsum placeat, corrupti dignissimos.</motion.p>
                        </div>
                        <motion.div variants={fadeIn}>
                            <Image src={'services-banner-1.png'} alt="" width={600} height={600} />
                        </motion.div>
                    </div>
                </div>
            </motion.section>

            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className="border-t border-white/20 py-20">
                <div className="container">

                    <div className="grid grid-cols-2 gap-x-5">
                        <motion.div variants={fadeIn}>
                            <p className="text-desc uppercase">{servicePriceItems[0].subtitle}</p>
                            <p className="text-5xl">${servicePriceItems[0].price}</p>
                        </motion.div>
                        <div className="space-y-2">
                            {servicePriceItems[0].texts.map(item => (
                                <motion.div variants={fadeIn} className="border border-white/20 p-5 flex items-center gap-x-3">
                                    <Image src={'star-shape.svg'} width={20} height={20} alt="" />
                                    <p>{item.text}</p>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-x-5 mt-10">
                        <motion.div variants={fadeIn}>
                            <p className="text-desc uppercase">{servicePriceItems[1].subtitle}</p>
                            <p className="text-5xl">${servicePriceItems[1].price}</p>
                        </motion.div>
                        <div className="space-y-2">
                            {servicePriceItems[1].texts.map(item => (
                                <motion.div variants={fadeIn} className="border border-white/20 p-5 flex items-center gap-x-3">
                                    <Image src={'star-shape.svg'} width={20} height={20} alt="" />
                                    <p>{item.text}</p>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-x-5 mt-10">
                        <motion.div variants={fadeIn}>
                            <p className="text-desc uppercase">{servicePriceItems[2].subtitle}</p>
                            <p className="text-5xl">${servicePriceItems[2].price}</p>
                        </motion.div>
                        <div className="space-y-2">
                            {servicePriceItems[2].texts.map(item => (
                                <motion.div variants={fadeIn} className="border border-white/20 p-5 flex items-center gap-x-3">
                                    <Image src={''} width={20} height={20} alt="" />
                                    <p>{item.text}</p>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                </div>
            </motion.section>

            {/* Events photography */}
            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className="my-10">
                <div className="container">
                    <div className="grid grid-cols-2 gap-10">
                        <div>
                            <motion.h3 variants={fadeIn} className="uppercase text-desc text-2xl mb-5">events photography</motion.h3>
                            <motion.p variants={fadeIn} className="text-desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi distinctio alias pariatur laboriosam magni corporis sapiente omnis natus rem. Maxime nihil dolorem molestiae quasi voluptas officia nemo excepturi unde voluptatibus quisquam assumenda amet animi, nisi exercitationem cumque quod quaerat? Culpa incidunt a ab mollitia aspernatur illo ipsum placeat, corrupti dignissimos.</motion.p>
                        </div>
                        <motion.div variants={fadeInOpacity}>
                            <Image src={'services-banner-2.jpg'} alt="" width={600} height={600} />
                        </motion.div>
                    </div>
                </div>
            </motion.section>
            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className="border-t border-white/20 py-20">
                <div className="container">

                    <div className="grid grid-cols-2 gap-x-5">
                        <motion.div variants={fadeIn}>
                            <p className="text-desc uppercase">{servicePriceItemsSecond[0].subtitle}</p>
                            <p className="text-5xl">${servicePriceItemsSecond[0].price}</p>
                        </motion.div>
                        <div className="space-y-2">
                            {servicePriceItemsSecond[0].texts.map(item => (
                                <motion.div variants={fadeIn} className="border border-white/20 p-5 flex items-center gap-x-3">
                                    <Image src={''} width={20} height={20} alt="" />
                                    <p>{item.text}</p>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-x-5 mt-10">
                        <motion.div variants={fadeIn}>
                            <p className="text-desc uppercase">{servicePriceItemsSecond[1].subtitle}</p>
                            <p className="text-5xl">${servicePriceItemsSecond[1].price}</p>
                        </motion.div>
                        <div className="space-y-2">
                            {servicePriceItemsSecond[1].texts.map(item => (
                                <motion.div variants={fadeIn} className="border border-white/20 p-5 flex items-center gap-x-3">
                                    <Image src={'star-shape.svg'} width={20} height={20} alt="" />
                                    <p>{item.text}</p>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-x-5 mt-10">
                        <motion.div variants={fadeIn}>
                            <p className="text-desc uppercase">{servicePriceItemsSecond[2].subtitle}</p>
                            <p className="text-5xl">${servicePriceItems[2].price}</p>
                        </motion.div>
                        <div className="space-y-2">
                            {servicePriceItemsSecond[2].texts.map(item => (
                                <motion.div variants={fadeIn} className="border border-white/20 p-5 flex items-center gap-x-3">
                                    <Image src={'star-shape.svg'} width={20} height={20} alt="" />
                                    <p>{item.text}</p>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                </div>
            </motion.section>

            {/* Commercial photography */}
            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className="my-10">
                <div className="container">
                    <div className="grid grid-cols-2 gap-10">
                        <div>
                            <motion.h3 variants={fadeIn} className="uppercase text-desc text-2xl mb-5">commercial photography</motion.h3>
                            <motion.p variants={fadeIn} className="text-desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi distinctio alias pariatur laboriosam magni corporis sapiente omnis natus rem. Maxime nihil dolorem molestiae quasi voluptas officia nemo excepturi unde voluptatibus quisquam assumenda amet animi, nisi exercitationem cumque quod quaerat? Culpa incidunt a ab mollitia aspernatur illo ipsum placeat, corrupti dignissimos.</motion.p>
                        </div>
                        <motion.div variants={fadeInOpacity}>
                            <Image src={'services-banner-3.jpg'} alt="" width={600} height={600} />
                        </motion.div>
                    </div>
                </div>
            </motion.section>
            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className="border-t border-white/20 py-20">
                <div className="container">

                    <div className="grid grid-cols-2 gap-x-5">
                        <motion.div variants={fadeIn}>
                            <p className="text-desc uppercase">{servicePriceItemsThird[0].subtitle}</p>
                            <p className="text-5xl">${servicePriceItemsThird[0].price}</p>
                        </motion.div>
                        <div className="space-y-2">
                            {servicePriceItemsThird[0].texts.map(item => (
                                <motion.div variants={fadeIn} className="border border-white/20 p-5 flex items-center gap-x-3">
                                    <Image src={'star-shape.svg'} width={20} height={20} alt="" />
                                    <p>{item.text}</p>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-x-5 mt-10">
                        <motion.div variants={fadeIn}>
                            <p className="text-desc uppercase">{servicePriceItemsThird[1].subtitle}</p>
                            <p className="text-5xl">${servicePriceItemsThird[1].price}</p>
                        </motion.div>
                        <div className="space-y-2">
                            {servicePriceItemsThird[1].texts.map(item => (
                                <motion.div variants={fadeIn} className="border border-white/20 p-5 flex items-center gap-x-3">
                                    <Image src={'star-shape.svg'} width={20} height={20} alt="" />
                                    <p>{item.text}</p>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                    <div className="grid grid-cols-2 gap-x-5 mt-10">
                        <motion.div variants={fadeIn}>
                            <p className="text-desc uppercase">{servicePriceItemsThird[2].subtitle}</p>
                            <p className="text-5xl">${servicePriceItemsThird[2].price}</p>
                        </motion.div>
                        <div className="space-y-2">
                            {servicePriceItemsThird[2].texts.map(item => (
                                <motion.div variants={fadeIn} className="border border-white/20 p-5 flex items-center gap-x-3">
                                    <Image src={'star-shape.svg'} width={20} height={20} alt="" />
                                    <p>{item.text}</p>
                                </motion.div>
                            ))}
                        </div>
                    </div>

                </div>
            </motion.section>

            <TitleName />
            <LineRun />
        </>
    )
}