import TitleSection from "@/components/TitleSection";
import { Metadata } from "next";
import { countUpItems, journeyItems } from "@/data/data";
import Image from "next/image";
import aboutImg from '../../public/about-page-banner.png'
import SliderTesti from "@/partials/SliderTesti";
import LineRun from "@/partials/LIneRun";
import * as motion from "motion/react-client"
import { containerStagger, fadeIn, fadeInOpacity } from "@/motion/animation";

export const metadata: Metadata = {
    title: 'About me - Photography as art',
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <>
            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className="mt-20">
                <div className="container">
                    <div className="flex justify-between items-center">
                        <TitleSection desc="about" title="about chris bloom" />
                    </div>
                    <div className="grid grid-cols-6 gap-x-5">
                        {countUpItems.map(item => (
                            <motion.div variants={fadeIn} className="bg-primary rounded-lg p-5 text-center">
                                <p className=" text-3xl">{item.value}</p>
                                <p className="text-desc">{item.text}</p>
                            </motion.div>
                        ))}
                    </div>
                    <motion.div variants={fadeInOpacity} className="">
                        <Image src={aboutImg} alt="" className="my-20" />
                    </motion.div>
                </div>
            </motion.section>
            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
            >
                <div className="container">
                    <motion.h3 variants={fadeIn} className="text-2xl uppercase">my biography</motion.h3>
                    <motion.p variants={fadeIn} className="text-desc mt-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia, quae. Veniam eius possimus quae neque consequatur. Porro, odio recusandae eligendi omnis quod sint nihil temporibus corrupti at consequatur optio reiciendis. Soluta facere modi enim rerum ad, illo totam suscipit iste porro ducimus ut dolorum est culpa, repellendus ipsa laudantium ab ea minima commodi perspiciatis illum vero et. Inventore alias hic sequi eum nostrum nihil sed minus aperiam quaerat, ratione suscipit architecto vitae molestiae autem nobis blanditiis delectus reprehenderit. Laboriosam voluptate vero veniam natus dolores placeat maiores ducimus quibusdam repellat, cum molestiae quidem, suscipit nobis sapiente ratione? Quas dolore voluptatem explicabo.</motion.p>
                </div>
            </motion.section>

            {/* Journey */}
            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className="my-30">
                <div className="container">
                    <div className="flex justify-between items-center">
                        <TitleSection desc="journey" title="chris journey - a timeline " />
                    </div>
                    <div className="grid grid-cols-2 gap-5">
                        {journeyItems.map(item => (
                            <motion.div variants={fadeIn} className="bg-primary rounded-lg p-5">
                                <div className="text-white/60 uppercase">{item.title}</div>
                                <p className="text-white/20">{item.text}</p>
                            </motion.div>
                        ))}
                    </div>
                </div>
            </motion.section>

            {/* Testimonials */}
            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
            >
                <div className="container">
                    <SliderTesti />
                </div>
            </motion.section>

            {/* TitleName */}
            <section className="pt-50 pb-20">
                <div className="container">
                    <h2 className="text-9xl text-primary text-end uppercase">Chris Bloom</h2>
                </div>
            </section>

            <LineRun />
        </>
    )
}