import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BtnUp from "@/components/BtnUp";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: {
    template: '%s | Chris Bloom',
    default: 'Chris Bloom - Photography as art"'
  },
  description: "Generated by create next app",
  icons: {
    icon: '/icon.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} bg-main text-white`}>
        <Header />
        {children}
        <Footer />
        <BtnUp />
      </body>
    </html>
  );
}
