import Image from 'next/image'
import portImg from '../../public/portfolio-page-banner.jpg'
import TitleSection from '@/components/TitleSection'
import SliderPortfolio from '@/partials/SliderPortfolio'
import { portfolioCardItems } from '@/data/data'
import FAQ from '@/partials/FAQ'
import TitleName from '@/partials/TitleName'
import LineRun from '@/partials/LIneRun'
import { Metadata } from 'next'
import * as motion from "motion/react-client"
import { containerStagger, fadeIn, fadeInOpacity } from '@/motion/animation'
import SliderPortraits from '@/partials/SliderPortraits'
import SliderEvents from '@/partials/SliderEvents'
import SliderCommercial from '@/partials/SliderCommercial'

export const metadata: Metadata = {
    title: 'Portfolio - Photography as art',
    description: "Generated by create next app",
};

export default function Page() {

    return (
        <>
            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className="py-20">
                <div className="container">
                    <div className="relative overflow-hidden">
                        <motion.div variants={fadeInOpacity} className="">
                            <Image src={portImg} alt='' className='rounded-2xl' />
                        </motion.div>
                        <div className="bg-main absolute top-0 left-0  max-w-140 p-5 rounded-br-2xl">
                            <div className="flex justify-between items-center">
                                <TitleSection desc="portfolio" title="visual poetry in pixels" />
                            </div>
                            <motion.p variants={fadeIn} className='text-desc'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci dicta fugit reprehenderit eaque esse qui voluptatem provident voluptatum nostrum ipsa.</motion.p>
                        </div>
                        <div className="bg-main absolute bottom-0 left-0 rounded-tr-2xl p-5">
                            <Image src={'/page-banner-shape.svg'} alt='' width={100} height={100} />
                        </div>
                        <div className="absolute bg-main p-5 bottom-0 right-0 text-desc rounded-tl-2xl">
                            Scroll down to see all the works
                        </div>
                    </div>
                </div>
            </motion.section>

            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className=''>
                <div className="container">
                    <SliderPortraits title={portfolioCardItems[0].title} list={portfolioCardItems[0].items} />
                </div>
            </motion.section>

            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className=''>
                <div className="container">
                    <SliderEvents title={portfolioCardItems[1].title} list={portfolioCardItems[1].items} />
                </div>
            </motion.section>

            <motion.section
                initial={'hidden'}
                whileInView={'visible'}
                variants={containerStagger}
                viewport={{ once: false }}
                className=''>
                <div className="container">
                    <SliderCommercial title={portfolioCardItems[2].title} list={portfolioCardItems[2].items} />
                </div>
            </motion.section>

            <FAQ />
            <TitleName />
            <LineRun />
        </>
    )
}